const STEERING_NONE = 0;
const STEERING_LEFT = 1;
const STEERING_RIGHT = 2;
const ATTR_GAME_MODEL = 100;
const ATTR_SPRITE_MGR = 102;
const ATTR_LANE = 103;
const ATTR_SPEED = 104;
const ATTR_OBSTACLE_MAP = 105;

const MSG_TOUCH = 103;
const MSG_ANIM_ENDED = 104;
const MSG_CAR_COLLIDED = 105;
const MSG_GAME_OVER = 106;
const MSG_IMMUNE_MODE_STARTED = 107;
const MSG_IMMUNE_MODE_ENDED = 108;

const LANES_NUM = 3;